server:
  port: 9093
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:placingordermSDb;DB_CLOSE_DELAY=-1
    username: sa
    password:  
    driver-class-name: org.h2.Driver 
  jpa:
    show-sql: true 

  application:
    name: placingorderms
