spring:
  cloud:
    config:
      enabled : false
      profile : native
      server:
        git:
          uri: https://github.com/nissipatrick/msrlabconfig.git
     
  
server:
  port: 8888
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
