security:
  oauth2:
    client:
      clientId: b4ee193f-debd-4052-aaee-2d22c146b52c
      clientSecret: M2UxZjA5M2QtZDVjOS00ZGVkLWI4ZTAtOTM2MGY5YjZkMDhk
      accessTokenUri: https://us-south.appid.cloud.ibm.com/oauth/v4/dfb2da70-a15e-47af-94a5-8ad7693d2bee/token
      userAuthorizationUri: https://us-south.appid.cloud.ibm.com/oauth/v4/dfb2da70-a15e-47af-94a5-8ad7693d2bee/authorization
    resource:
      userInfoUri: https://us-south.appid.cloud.ibm.com/oauth/v4/dfb2da70-a15e-47af-94a5-8ad7693d2bee/userinfo
      


